### ISSUE TITLE
WARNING on run

### ISSUE THREAD

**Issue by ronencamera** [ptkach/fileDroppa#37] opened 2016-03-29 09:31 UTC
i am receiving the following WARNING. Any idea why?

```
WARNING in ./~/file-droppa/index.js
Cannot find SourceMap 'index.js.map': Error: Cannot resolve 'file' or 'directory' ./index.js.map in /Users/usera/Documents/projects/starter/node_modules/file-droppa

WARNING in ./~/file-droppa/components/Services/FileStore.service.js
Cannot find SourceMap 'FileStore.service.js.map': Error: Cannot resolve 'file' or 'directory' ./FileStore.service.js.map in /Users/usera/Documents/projects/starter/node_modules/file-droppa/components/Services

WARNING in ./~/file-droppa/components/Directives/FileDropZone.js
Cannot find SourceMap 'FileDropZone.js.map': Error: Cannot resolve 'file' or 'directory' ./FileDropZone.js.map in /Users/usera/Documents/projects/starter/node_modules/file-droppa/components/Directives

WARNING in ./~/file-droppa/components/Directives/FileDroppa.js
Cannot find SourceMap 'FileDroppa.js.map': Error: Cannot resolve 'file' or 'directory' ./FileDroppa.js.map in /Users/usera/Documents/projects/starter/node_modules/file-droppa/components/Directives

WARNING in ./~/file-droppa/components/Directives/FileList.js
Cannot find SourceMap 'FileList.js.map': Error: Cannot resolve 'file' or 'directory' ./FileList.js.map in /Users/usera/Documents/projects/starter/node_modules/file-droppa/components/Directives

WARNING in ./~/file-droppa/components/Services/FileWrapper.service.js
Cannot find SourceMap 'FileWrapper.service.js.map': Error: Cannot resolve 'file' or 'directory' ./FileWrapper.service.js.map in /Users/usera/Documents/projects/starter/node_modules/file-droppa/components/Services

WARNING in ./~/file-droppa/components/Services/FileParser.service.js
Cannot find SourceMap 'FileParser.service.js.map': Error: Cannot resolve 'file' or 'directory' ./FileParser.service.js.map in /Users/usera/Documents/projects/starter/node_modules/file-droppa/components/Services

WARNING in ./~/file-droppa/components/Directives/File.js
Cannot find SourceMap 'File.js.map': Error: Cannot resolve 'file' or 'directory' ./File.js.map in /Users/usera/Documents/projects/starter/node_modules/file-droppa/components/Directives

WARNING in ./~/file-droppa/components/Services/FileUpload.service.js
Cannot find SourceMap 'FileUpload.service.js.map': Error: Cannot resolve 'file' or 'directory' ./FileUpload.service.js.map in /Users/usera/Documents/projects/starter/node_modules/file-droppa/components/Services

WARNING in ./~/file-droppa/components/Pipes/GetSize.pipe.js
Cannot find SourceMap 'GetSize.pipe.js.map': Error: Cannot resolve 'file' or 'directory' ./GetSize.pipe.js.map in /Users/usera/Documents/projects/starter/node_modules/file-droppa/components/Pipes

```

**Comment by ptkach** [comment] 2016-03-29 14:15
Hi,
Source-maps are generated automatically by typescript + webpack. Looks like you have in configuration source-map enabled, but you don't have them generated. I use webpack config with following information to generate them:

`    output: {
        path: absDest,
        filename: '[name].js',
        sourceMapFilename: '[name].js.map',
        chunkFilename: '[id].chunk.js'
    },`

Let me know if it works or you.

**Comment by ronencamera** [comment] 2016-03-29 14:26
i am using https://github.com/AngularClass/angular2-webpack-starter <https://github.com/AngularClass/angular2-webpack-starter> for my project. 

i am changes as you said, still have the warnings.

**Comment by ptkach** [comment] 2016-03-29 14:52
The problem is in your webpack config somewhere for sure.

1. First of all I would suggest you to figure what source-map files he is generating, might be he is generating File.map, but looking for File.js.map for example.

2. If you can't find the right place to fix you can always exclude file-droppa from source-map-loader in preLoaders section. That will help you get rid of warnings.

**Comment by ptkach** [comment] 2016-03-30 13:37
I'm closing it since there's nothing related to lib itself

**Closed by ptkach** 2016-03-30 13:37 UTC
